name: Generate Snake

on:
  schedule: # Ejecutar todos los días a la medianoche
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Generar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: TU-USUARIO
          outputs: dist/github-contribution-grid-snake.svg

      - name: Subir Snake al repositorio
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
